---
apiVersion: apps/v1
kind: Pod
metadata:
  name: my-pod-webserver
  labels:
    name: my-pod-webserver
spec:
  containers:
  - name: my-mod-nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
